Section2_Projects/Program3/pizza/pizzas/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'pizzas'
urlpatterns = [
    #homepage
    path('', views.index, name='index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza')
]

Section2_Projects/Program3/pizza/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

Section2_Projects/Program3/pizza/pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    """ define a model named Pizza"""
    name = models.CharField(max_length=50)

    def __str__(self):
        """ return name"""
        return self.name.title()

class Topping(models.Model):
    """
    pizza - foreignkey - Pizza
    name - put dosings
    """
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    class Meta:
        verbose_name_plural = 'topping'

    def __str__(self):
        return self.name

Section2_Projects/Program3/pizza/pizzas/views.py
""" define pizzas' URL pattern"""

from django.shortcuts import render
from .models import Pizza

# Create your views here.
def index(request):
    """ pizzas' index page"""
    return render(request, 'pizzas/index.html')


def pizzas(request):
    """ show all pizzas """
    pizzas = Pizza.objects.order_by('name')
    p_names = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', p_names)


def pizza(request, pizza_id):
    """ show single pizza and its details"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

Section2_Projects/Program3/pizza/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index'%}">Pizzas_Home_Page</a>
    <a href="{% url 'pizzas:pizzas'%}">Pizzas</a>
</p>

{% block content %} {% endblock content%}

Section2_Projects/Program3/pizza/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
    <p>The contents show pizzas and its toppings.</p>
{% endblock content %}

Section2_Projects/Program3/pizza/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizza Name: {{ pizza }}</p>

    <p>Toppings:</p>
    <ul>
        {% for topping in toppings %}
            <li>
                <!--<p>{{ topping.pizza}}</p>-->
                <p>{{ topping }}</p>
            </li>
        {% empty %}
            <li>
                There are no entries for this topic yet.
            </li>
        {% endfor %}
    </ul>

{% endblock content %}

Section2_Projects/Program3/pizza/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
    <p>Pizzas</p>
    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">{{pizza}}</a>
            </li>
        {% empty %}
            <li>No objects have been added yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}